// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cppForest
List cppForest(NumericMatrix& x, NumericVector& y, int nSamp, int nodeSize, int maxNodes, int nTree, int mtry, int keepF, int replace, int classify);
RcppExport SEXP surfin_cppForest(SEXP xSEXP, SEXP ySEXP, SEXP nSampSEXP, SEXP nodeSizeSEXP, SEXP maxNodesSEXP, SEXP nTreeSEXP, SEXP mtrySEXP, SEXP keepFSEXP, SEXP replaceSEXP, SEXP classifySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nSamp(nSampSEXP);
    Rcpp::traits::input_parameter< int >::type nodeSize(nodeSizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxNodes(maxNodesSEXP);
    Rcpp::traits::input_parameter< int >::type nTree(nTreeSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type keepF(keepFSEXP);
    Rcpp::traits::input_parameter< int >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< int >::type classify(classifySEXP);
    __result = Rcpp::wrap(cppForest(x, y, nSamp, nodeSize, maxNodes, nTree, mtry, keepF, replace, classify));
    return __result;
END_RCPP
}
// cppMatch
DataFrame cppMatch(IntegerVector tr, NumericVector dist, char type);
RcppExport SEXP surfin_cppMatch(SEXP trSEXP, SEXP distSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type tr(trSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    __result = Rcpp::wrap(cppMatch(tr, dist, type));
    return __result;
END_RCPP
}
// cppPredict
NumericVector cppPredict(NumericMatrix x, IntegerMatrix splitVar, NumericMatrix split, IntegerMatrix lDaughter, IntegerMatrix rDaughter, NumericMatrix nodePred);
RcppExport SEXP surfin_cppPredict(SEXP xSEXP, SEXP splitVarSEXP, SEXP splitSEXP, SEXP lDaughterSEXP, SEXP rDaughterSEXP, SEXP nodePredSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type splitVar(splitVarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type split(splitSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type lDaughter(lDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rDaughter(rDaughterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nodePred(nodePredSEXP);
    __result = Rcpp::wrap(cppPredict(x, splitVar, split, lDaughter, rDaughter, nodePred));
    return __result;
END_RCPP
}
// cppProx
arma::mat cppProx(arma::umat nodes);
RcppExport SEXP surfin_cppProx(SEXP nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::umat >::type nodes(nodesSEXP);
    __result = Rcpp::wrap(cppProx(nodes));
    return __result;
END_RCPP
}
