# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' cppMatch
#' @description
#' Nearest neighbor 1:1 matching within and between conditions. 
#' @param tr vector
#' @param dist distance
#' @param type corresponds to R's representation of distance. 'v' = vector of pairwise distances (class "dist"), 'm' = matrix of pairwise distances (coerced as a vector), 'p' = vector of propensity scores
#' @details
#' Ties are broken using the the first match (not randomly).
#' @export
cppMatch <- function(tr, dist, type) {
    .Call('proxMatch_cppMatch', PACKAGE = 'proxMatch', tr, dist, type)
}

#' @title
#' cppForest
#' @description
#' Construct random forest
#' @param x matrix
#' @param y vector
#' @param nSamp number of samples
#' @param nodeSize node size
#' @param maxNodes maximum number of nodes
#' @param nTree number of trees desired
#' @param mtry tuning
#' @param keepF keep forest or not
#' @param replace bootstrap samples or subsamples
#' @param classify perform classification or regression
#' @details
#' Options available for bootstrap samples or subsamples
#' @export
cppForest <- function(x, y, nSamp, nodeSize, maxNodes, nTree, mtry, keepF, replace, classify) {
    .Call('proxMatch_cppForest', PACKAGE = 'proxMatch', x, y, nSamp, nodeSize, maxNodes, nTree, mtry, keepF, replace, classify)
}

#' @title
#' cppProx
#' @description
#' Given an n x nTree matrix of terminal nodes, this function will return an n x n proximimity matrix.
#' @param nodes n x nTree matrix of terminal nodes
#' @details
#' The computed proximities are based on only the out-of-bag predictions. Zero-valued entries in nodes correspond to in-bag instances.
#' @export
cppProx <- function(nodes) {
    .Call('proxMatch_cppProx', PACKAGE = 'proxMatch', nodes)
}

#' @title
#' cppPredict
#' @description
#' Returns predictions from a stored forest.
#' @param x = matrix of covariates for the test data
#' @param splitVar  = best split variables
#' @param split     = best split values
#' @param lDaughter = left daughter node assignments
#' @param nnodePred = terminal node predictions
#' @details
#' All other matrices represent the forest. Trees are columns, and nodes are rows.
#' @export
cppPredict <- function(x, splitVar, split, lDaughter, rDaughter, nodePred) {
    .Call('proxMatch_cppPredict', PACKAGE = 'proxMatch', x, splitVar, split, lDaughter, rDaughter, nodePred)
}

#'@importFrom Rcpp evalCpp
#'@useDynLib proxMatch

